### ISSUE TITLE
Add what institution acronyms mean

### ISSUE THREAD

**Issue by j-harbin** [dankelley/argoFloats#65]

**Comment by j-harbin** [comment]
This is complete, however, I thought it was worth noting that when doing the following code:

```-R
aii <-getIndex(file='merge', destdir = "~/data/argo")
sort(unique(unlist(strsplit(aii@data$index$institution, ' '))))
```
I receive:
`
[1] "AO" "BO" "CS" "HZ" "IF" "IN" "JA" "KM" "KO" "ME"
`

However, when looking at Table 4 in the Argo User's Manual (referenced below), there are a variety of institutions that are not included within this index.

Carval, Thierry, Bob Keeley, Yasushi Takatsuki, Takashi Yoshida, Stephen Loch, Claudia Schmid, Roger Goldsmith et al. "Argo User's Manual, Version 3.2. December 29th 2015.[SUPERSEDED]." (2015).

**Comment by dankelley** [comment]
This looks good.  A few small points are below.  If you're not editing the file right now, I could change these -- it might be easier than suggesting precise edits. So, maybe let me know if I can change in "develop" on a certain timescale...

1. I find the wording of items 6 and 8 a bit confusing. Maybe it should say e.g. "a list holding a character value naming the institution (see example x)" etc.  

2. There ought to be an example for the institution.  Basically, each item in the enumerated list ought to have an example with the same key number, to make it easier for people.  Right now, item 8 in the list maps to example 6, which is a bit confusing.

3. It can be *really* hard to get wording exactly right. Sometimes it can be easier to just say something approximately in the words, if you have an example.  then we don't have to be too careful about writing perfect sentences.

4. The list of things should be e.g. `"AO"` and not `AO`, since it is a character item.

5. I don't know why some items say "which has argo, argo_bgc, or argo_merge institutions" because this actually applies to any variety.  I thik it should say "which has institution codes" or something like that.

6. It can be *really* hard to get wording exactly right. Sometimes it can be easier to just say something approximately in the words, if you have an example.  then we don't have to be too careful about writing perfect sentences.


<img width="538" alt="Screen Shot 2020-04-15 at 1 52 58 PM" src="https://user-images.githubusercontent.com/99469/79364994-706b9080-7f20-11ea-995f-78116ba8c72b.png">

**Comment by j-harbin** [comment]
All great points! Feel free to work within develop. I am only working within my sandbox.

**Comment by dankelley** [comment]
Thanks. I'm done now.

It might help if you could skim through my wording, @j-harbin, because we want this to be clear, now that we're at it.

PS. I don't know if the colours in the example (shown blow) will be ok for people with problems viewing colour.

![image](https://user-images.githubusercontent.com/99469/79369358-3487f980-7f27-11ea-98e5-700ddef1f2a8.png)
